advanced:
  batch_send_interval: 3
  batch_size:
    bark: 4000
    default: 4000
    dingtalk: 20000
    feishu: 30000
    slack: 4000
  configs_version_check_url: https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version_configs
  crawler:
    default_proxy: http://127.0.0.1:10801
    request_interval: 2000
    use_proxy: false
  debug: false
  feishu_message_separator: ━━━━━━━━━━━━━━━━
  max_accounts_per_channel: 3
  mcp_version_check_url: https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version_mcp
  rss:
    proxy_url: ''
    request_interval: 1000
    timeout: 15
    use_proxy: false
  version_check_url: https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version
  weight:
    frequency: 0.3
    hotness: 0.1
    rank: 0.6
ai:
  api_base: ''
  api_key: ''
  fallback_models: []
  max_tokens: 5000
  model: deepseek/deepseek-chat
  num_retries: 1
  temperature: 1.0
  timeout: 120
ai_analysis:
  enabled: false
  include_rank_timeline: true
  include_rss: false
  include_standalone: true
  language: Chinese
  max_news_for_analysis: 150
  mode: follow_report
  prompt_file: ai_analysis_prompt.txt
ai_filter:
  batch_interval: 2
  batch_size: 200
  extract_prompt_file: extract_prompt.txt
  min_score: 0.7
  prompt_file: prompt.txt
  reclassify_threshold: 0.6
  update_tags_prompt_file: update_tags_prompt.txt
ai_translation:
  enabled: true
  language: 中文
  prompt_file: ai_translation_prompt.txt
  scope:
    hotlist: false
    rss: true
    standalone: true
app:
  show_version_update: true
  timezone: Asia/Shanghai
display:
  region_order:
  - new_items
  - hotlist
  - rss
  - standalone
  - ai_analysis
  regions:
    ai_analysis: true
    hotlist: true
    new_items: false
    rss: true
    standalone: false
  standalone:
    max_items: 20
    platforms:
    - zhihu
    - wallstreetcn-hot
    rss_feeds: []
filter:
  method: keyword
  priority_sort_enabled: true
notification:
  channels:
    bark:
      url: ''
    dingtalk:
      webhook_url: ''
    email:
      from: ''
      password: ''
      smtp_port: ''
      smtp_server: ''
      to: ''
    feishu:
      webhook_url: https://open.feishu.cn/open-apis/bot/v2/hook/31180691-a9c9-4456-81b6-424d28fab850
    generic_webhook:
      payload_template: ''
      webhook_url: ''
    ntfy:
      server_url: https://ntfy.sh
      token: ''
      topic: ''
    slack:
      webhook_url: ''
    telegram:
      bot_token: ''
      chat_id: ''
    wework:
      msg_type: markdown
      webhook_url: ''
  enabled: true
platforms:
  enabled: true
  sources:
  - id: toutiao
    name: 今日头条
  - id: baidu
    name: 百度热搜
  - id: wallstreetcn-hot
    name: 华尔街见闻
  - id: thepaper
    name: 澎湃新闻
  - id: bilibili-hot-search
    name: bilibili 热搜
  - id: cls-hot
    name: 财联社热门
  - id: ifeng
    name: 凤凰网
  - id: tieba
    name: 贴吧
  - id: weibo
    name: 微博
  - id: douyin
    name: 抖音
  - id: zhihu
    name: 知乎
report:
  display_mode: keyword
  max_news_per_keyword: 0
  mode: current
  rank_threshold: 5
  sort_by_position_first: false
rss:
  enabled: true
  feeds:
  - id: hacker-news
    name: Hacker News
    url: https://hnrss.org/frontpage
  - enabled: false
    id: ruanyifeng
    name: 阮一峰的网络日志
    url: http://www.ruanyifeng.com/blog/atom.xml
  - id: yahoo-finance
    name: 雅虎财经
    url: https://finance.yahoo.com/news/rssindex
  freshness_filter:
    enabled: true
    max_age_days: 1
schedule:
  enabled: true
  preset: morning_evening
storage:
  backend: auto
  formats:
    html: true
    sqlite: true
    txt: false
  local:
    data_dir: output
    retention_days: 0
  pull:
    days: 7
    enabled: false
  remote:
    access_key_id: ''
    bucket_name: ''
    endpoint_url: ''
    region: ''
    retention_days: 0
    secret_access_key: ''
